# Generated by Django 4.0 on 2023-04-20 09:40

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('allapps_user', '0002_user_offers_liked'),
        ('allapps_offer', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('body', models.TextField()),
                ('edited', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allapps_user.user')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allapps_offer.offer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
