# Generated by Django 4.0 on 2023-04-19 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allapps_offer', '0002_initial'),
        ('allapps_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='offers_liked',
            field=models.ManyToManyField(related_name='liked_by', to='allapps_offer.Offer'),
        ),
    ]
